package resources

const (
  SERVER_ADDR_FLAG = "SERVER_ADDR"
  SERVER_ADDR = "127.0.0.1"
  SERVER_PORT = 9323
  USE_TLS_FLAG = "USE_TLS"
  TLS_KEY_FLAG = "TLS_KEY"
  TLS_CERT_FLAG = "TLS_CERT"
  PORT_FLAG = "PORT"
)
